// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJccKh-CVwF2JNR7DFWZxP-wg1jlhFqU',
    appId: '1:1071652904865:web:6214c419e4174c92e135e0',
    messagingSenderId: '1071652904865',
    projectId: 'demoapp-c337e',
    authDomain: 'demoapp-c337e.firebaseapp.com',
    databaseURL: 'https://demoapp-c337e-default-rtdb.firebaseio.com',
    storageBucket: 'demoapp-c337e.appspot.com',
    measurementId: 'G-PVZCM2LZGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZCOUS8OgTRwj6je-Cdqk7PWG7od1iAA',
    appId: '1:1071652904865:android:5258c9afa0da6e3de135e0',
    messagingSenderId: '1071652904865',
    projectId: 'demoapp-c337e',
    databaseURL: 'https://demoapp-c337e-default-rtdb.firebaseio.com',
    storageBucket: 'demoapp-c337e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFO2Vuusnsp1nh0uU83qwSWEAHAzqfPlQ',
    appId: '1:1071652904865:ios:db25ff447a6b3d9de135e0',
    messagingSenderId: '1071652904865',
    projectId: 'demoapp-c337e',
    databaseURL: 'https://demoapp-c337e-default-rtdb.firebaseio.com',
    storageBucket: 'demoapp-c337e.appspot.com',
    iosBundleId: 'com.example.clickCounter',
  );
}
